import { getWallpapersCount } from "@/models/wallpaper";

export default async function () {
  const total = await getWallpapersCount();

  return (
    <>
      <h1 className="my-5 text-center text-3xl font-bold sm:text-4xl md:text-5xl lg:text-6xl text-primary">
        AI Wallpaper Generator
      </h1>
      <h2 className="mx-auto mb-4 text-center text-sm text-[#636262] sm:h2x-8 sm:text-xl md:px-24 lg:mb-4">
        <span className="text-primary">{total}</span> wallpapers generated by AI
      </h2>
    </>
  );
}
